// Generated by CoffeeScript 1.10.0
(function() {
  var Balloon, balloonEl, balloons, bg, canvas, context, drawLoop;

  canvas = document.getElementById('canvas');

  context = canvas.getContext('2d');

  bg = document.getElementById('bg');

  balloonEl = document.getElementById('balloon');

  balloons = [];

  Balloon = (function() {
    function Balloon(x, y) {
      this.x = x;
      this.y = y;
      this.created = Date.now();
    }

    return Balloon;

  })();

  canvas.height = window.innerHeight;

  canvas.width = window.innerWidth;

  canvas.addEventListener('click', function(e) {
    return balloons.push(new Balloon(e.clientX, e.clientY));
  });

  drawLoop = function() {
    var balloon, i, j, len, timeSinceCreation, x, y;
    context.clearRect(0, 0, canvas.width, canvas.height);
    context.drawImage(bg, 0, 0);
    for (i = j = 0, len = balloons.length; j < len; i = ++j) {
      balloon = balloons[i];
      x = balloon != null ? balloon.x : void 0;
      y = balloon != null ? balloon.y : void 0;
      timeSinceCreation = Date.now() - (balloon != null ? balloon.created : void 0);
      context.drawImage(balloonEl, x, y);
      if (timeSinceCreation < 500) {
        balloon.y -= 4;
      }
      if (timeSinceCreation >= 500 && timeSinceCreation < 1000) {
        balloon.y -= 5;
      }
      if (timeSinceCreation >= 1000) {
        balloon.y -= 7;
      }
      if (y <= -151) {
        balloons.splice(i, 1);
      }
    }
    return requestAnimationFrame(drawLoop);
  };

  drawLoop();

}).call(this);
